production:
  database:
    mongoclient: mongodb+srv://achyutammehta:7WvgmzWySS2wCLin@workannivcluster.cbvgni6.mongodb.net/?retryWrites=true&w=majority
    db_name: WorkAnnivDataHub
    collection_name: EmployeeAnniversaryRecords

  file_path:
    downloaded_images: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Downloaded_Images
    log_path: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Logs\wzb_work_anniversary_greetings_automation
    data_add_loader_log: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Logs\Data_Add_Loader
    data_add_loader: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Data Add Loader
    loader_backup: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Data Add Loader Backup

development:
  database:
    mongoclient: mongodb+srv://achyutammehta:7WvgmzWySS2wCLin@workannivcluster.cbvgni6.mongodb.net/?retryWrites=true&w=majority
    db_name: WorkAnnivDataHub
    collection_name: EmployeeAnniversaryRecords

  file_path:
    downloaded_images: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Downloaded_Images
    log_path: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Logs\wzb_work_anniversary_greetings_automation
    data_add_loader_log: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Logs\Data_Add_Loader
    data_add_loader: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Data Add Loader
    loader_backup: C:\Python\WBZ_Work_Anniversary_Greetings_Automation\Data\Data Add Loader Backup